name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SamiMadane
          outputs: |
            dist/snake.svg

      - name: Commit and Push to output branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          branch: output
          file_pattern: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
